apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - order-api.yaml
  - order-api-service.yaml
  - order-api-ingress.yaml
images:
  - name: order-api
    newName: rafaelbarbosa09/order-api
    newTag: 0.1.0