apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  labels:
    app: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: order-api
        ports:
        - containerPort: 3000
        env:
          - name: RABBIT_HOST
            value: broker
          - name: RABBIT_PORT
            value: "5672"
          - name: RABBIT_USER
            valueFrom:
              secretKeyRef:
                name: rabbit-user
                key: username
          - name: RABBIT_PASS
            valueFrom:
              secretKeyRef:
                name: rabbit-user
                key: password
          - name: HOST_DB
            valueFrom:
              secretKeyRef:
                name: order-db-user
                key: host
          - name: USER_DB
            valueFrom:
              secretKeyRef:
                name: order-db-user
                key: user
          - name: PASS_DB
            valueFrom:
              secretKeyRef:
                name: order-db-user
                key: pass
          - name: PORT_DB
            valueFrom:
              secretKeyRef:
                name: order-db-user
                key: port
          - name: NAME_DB
            valueFrom:
              secretKeyRef:
                name: order-db-user
                key: db
          - name: QUEUE_PAYMENT_REQUEST
            value: beta.payment.request
          - name: QUEUE_PAYMENT_RESPONSE
            value: beta.payment.response
          - name: QUEUE_SUBSCRIPTIONS
            value: subscription_created
